# Generated by Django 5.1.4 on 2024-12-20 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labyrinth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_repreesntation', models.CharField(max_length=4096)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LabyrinthTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=1)),
                ('neighbor_north', models.CharField(max_length=1)),
                ('neighbor_south', models.CharField(max_length=1)),
                ('neighbor_east', models.CharField(max_length=1)),
                ('neighbor_west', models.CharField(max_length=1)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('labyrinth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labyrinth.labyrinth')),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('symbol', models.CharField(max_length=1, unique=True)),
                ('labyrinth', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='labyrinth.labyrinth')),
                ('current_tile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='labyrinth.labyrinthtile')),
            ],
        ),
    ]
