version: "3.7"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=geheim
      - POSTGRES_DB=clp
      - PGUSER=client
      - PGPASSWORD=geheim
      - PGDATABASE=clp
    volumes:
      - ./docker_compose/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "client", "-d", "clp"]
      interval: 1s
      timeout: 5s
      retries: 10

